# Launch EC2 Instances
- name: Ansible test
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: launching ops manager instance
      ec2:
        profile: default
        instance_type: t3.xlarge
        image: ami-0155ce198ae244377
        wait: yes
        count: 1 
        assign_public_ip: yes
        vpc_subnet_id: subnet-53f0df19
        region: us-east-2
        key_name: gskygrogan_cmdemo
        instance_tags:
          Name: mside_launched_om_instances
          owner: "{{ ownerUserName }}"
          expire-on: "{{ expireon }}"
          purpose: "training"
      register: ec2
    - debug:
        msg:
        - "{{ ec2 }}"
        - "YOUR INSTANCE IS READY."
        - "Scroll up into the JSON right above here to see the ec2 instance name and URL should look like http://ec2-18-221-183-58.us-east-2.compute.amazonaws.com:8080"
        - "Just create a new Ops Manager user from the login page"
